# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0cf0dd53b4122a198452a2d2c51f379ee481e26e5aef1136940dd11783e953ecd166b8e9efa9b3b3a53385380921b33ad073cc8fa424cc62318a3e28797f73

test:
  secret_key_base: 0abd28987df321e41479dd6f2caba89996c110c5e997e80d391b3477fa15984f83025f35ca1683e38b49fb72a1c7dc5a0fffc71371f04f798b3a90129f81a5f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
